### ISSUE TITLE
Cannot run the tests nor the samples.

### ISSUE THREAD

**Issue by fhoubie** [Oslandia/py3dtiles#25] opened 2018-09-26 14:06 UTC
Hi, I'm trying to compile py3Dtiles. It works, but I can't run the tests neither the example

(venv) LEU-XFHOUBIE01:py3dtiles fhoubie$ nosetests
.......EEEEE.E
======================================================================
ERROR: tests.test_points.test_grid_insert
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_grid_insert() missing 2 required positional arguments: 'grid' and 'node'

======================================================================
ERROR: tests.test_points.test_grid_insert_perf
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_grid_insert_perf() missing 3 required positional arguments: 'grid', 'node', and 'benchmark'

======================================================================
ERROR: tests.test_points.test_grid_getpoints
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_grid_getpoints() missing 2 required positional arguments: 'grid' and 'node'

======================================================================
ERROR: tests.test_points.test_grid_getpoints_perf
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_grid_getpoints_perf() missing 3 required positional arguments: 'grid', 'node', and 'benchmark'

======================================================================
ERROR: tests.test_points.test_grid_get_point_count
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_grid_get_point_count() missing 2 required positional arguments: 'grid' and 'node'

======================================================================
ERROR: tests.test_points.test_is_point_far_enough_perf
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_is_point_far_enough_perf() missing 1 required positional argument: 'benchmark'

----------------------------------------------------------------------
Ran 14 tests in 0.523s

FAILED (errors=6)

(venv) LEU-XFHOUBIE01:tests fhoubie$ py3dtiles info tests/pointCloudRGB.pnts
Traceback (most recent call last):
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/bin/py3dtiles", line 11, in <module>
    load_entry_point('py3dtiles==1.1.0', 'console_scripts', 'py3dtiles')()
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/py3dtiles-1.1.0-py3.6.egg/py3dtiles/command_line.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/py3dtiles-1.1.0-py3.6.egg/py3dtiles/convert.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/py3dtiles-1.1.0-py3.6.egg/py3dtiles/points/node.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/py3dtiles-1.1.0-py3.6.egg/py3dtiles/points/points_grid.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/py3dtiles-1.1.0-py3.6.egg/py3dtiles/points/distance.py", line 5, in <module>
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/numba/decorators.py", line 191, in wrapper
    disp.enable_caching()
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 566, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/numba/caching.py", line 614, in __init__
    self._impl = self._impl_class(py_func)
  File "/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/numba/caching.py", line 349, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function 'is_point_far_enough': no locator available for file '/Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/py3dtiles-1.1.0-py3.6.egg/py3dtiles/points/distance.py'

List of installed modules : 
(venv) LEU-XFHOUBIE01:py3dtiles fhoubie$ pip list
Package         Version  Location
--------------- -------- --------------------------------------------------------------------------------------------------------
atomicwrites    1.2.1
attrs           18.2.0
Cython          0.28.5
laspy           1.5.1
libLAS          1.8.1
llvmlite        0.25.0
lz4             2.1.0
more-itertools  4.3.0
nose            1.3.7
numba           0.40.0
numpy           1.15.2
pip             18.0
pluggy          0.7.1
psutil          5.4.7
psycopg2-binary 2.7.5
py              1.6.0
py3dtiles       1.1.0    /Users/fhoubie/Dev/github/Ostlandia/py3dtiles/venv/lib/python3.6/site-packages/py3dtiles-1.1.0-py3.6.egg
pyproj          1.9.5.1
pytest          3.8.1
pyzmq           17.1.2
setuptools      40.4.3
six             1.11.0
triangle        20170429
wheel           0.31.1

Do you know if there is something wrong in the code or in my installation ?

Thanks
Frédéric

**Comment by peppsac** [comment] 2018-09-27 14:34
The first issue (`nosetests` command failing) has been fixed by #26 : we don't use `nosetests` anymore, please use `pytest` instead. 

The second problem (` RuntimeError: cannot cache function 'is_point_far_enough': no locator available for file [...]`) seems to be a numba issue on your machine: numba fails to write to its disk cache. Maybe a permissions issue?

**Comment by ghost** [comment] 2018-10-02 15:01
Hi,

@peppsac I had exact same error as (RuntimeError: cannot cache function 'is_point_far_enough': no locator available for file [...]) . It doesn't seem like a permission issue.
@fhoubie Did you fix that?

Thanks,
Wang

**Comment by fhoubie** [comment] 2018-10-02 15:05
Hi @shiruiwang , 

unfortunately not. I've tried some hints found on some forums, but no way to solve it. It is indeed not a permission issue.

Thanks
Frédéric

**Comment by ghost** [comment] 2018-10-02 15:12
Hi @fhoubie ,

thanks for your quick reply. 
I recall that long time ago (a year or two) I've tried this tool and it worked fine to get .pnts info. Maybe they have changed a lot since then.
Perhaps @peppsac could give us some ideas.

Cheers,
Wang

**Comment by peppsac** [comment] 2018-10-03 14:16
@shiruiwang :
> @peppsac I had exact same error as (RuntimeError: cannot cache function 'is_point_far_enough': no locator available for file [...]) . It doesn't seem like a permission issue.

What platform are you using? How did you install `py3dtiles`?

@ both of you:
This [question](https://stackoverflow.com/questions/44183779/numba-caching-issue-cannot-cache-function-no-locator-available-for-file) refers to the file [caching.py](https://github.com/numba/numba/blob/master/numba/caching.py) from numba.

It would be interesting to add some comment in the various `_locator_classes` `from_function` implementation, to understand exactly the issue.

**Comment by EricBoix** [comment] 2018-10-04 09:30
Platform: 
  - OSX-10.13.6, 
   - Python 3.6.5 (installed with homebrew)

Install: 
  - followed the Readme.rst including the `(venv)$ python setup.py install` of the last line 
  - note: I had to use `virtualenv -p python3 venv` instead of `virtualenv -p /usr/bin/python3 venv` that unnecessarily hard-wires the path to `/usr/bin/python3` (when the python3 found in my path happens to be `/usr/local/bin/python3` because of a homebrew package install) 

Running the tests with`pytest` worked flawlessly for me.

But when running the first info example `py3dtiles info tests/pointCloudRGB.pnts` I get the same (mutatis mutandis for pathes) error as @fhoubie.

The main google reference I could find is also the [StackOverflow entry](https://stackoverflow.com/questions/44183779/numba-caching-issue-cannot-cache-function-no-locator-available-for-file) (pointed above by @peppsac ). Because of a note of Gregg Jennings on that StackOverflow (and also because of [this numba issue](https://github.com/numba/numba/issues/1771)), I went fooling around with some `chmod o+w <dir>` on various directories encountered on the path of the installed py3dTiles but without "luck".

As suggested in the single answer (by user2297529) [StackOverflow entry](https://stackoverflow.com/questions/44183779/numba-caching-issue-cannot-cache-function-no-locator-available-for-file),  I also tried patching `caching.py` with the line `sys.frozen = True` but it didn't help.

I went tracing `caching.py` as suggested by @peppsac. Here is what I learned about the flow to the error within `caching.py`:
 - The error gets triggered by [line 344 ](https://github.com/numba/numba/blob/master/numba/caching.py#L344) for `cls` with value `numba.caching._IPythonCacheLocator` (that is the last possible locator [`self._locator_classes`](https://github.com/numba/numba/blob/master/numba/caching.py#L328))
 -  the [corresponding from_function (line 308)](https://github.com/numba/numba/blob/master/numba/caching.py#L308) get called with the following arguments
     * `py_func:  <function is_point_far_enough at 0x11715e158>`
     *  `py_file:  /Users/ebo/UNSAVED/tmp/py3dtiles.MEPP-team.reference/venv/lib/python3.6/site-packages/py3dtiles-1.1.0-py3.6.egg/py3dtiles/points/distance.py`
 - Within that function the [following test `if not py_file.startswith("<ipython-"):`](https://github.com/numba/numba/blob/master/numba/caching.py#L309) (on line 309) being true, the function returns with a None result
 -  Returning to the calling [__init() method](https://github.com/numba/numba/blob/master/numba/caching.py#L347) (line 347), and no locator having been found, the error is raised.

Hence the error is simply thrown because no known locator has been found for that file. 

Since [the docstring of `_UserProvidedCacheLocator`](https://github.com/numba/numba/blob/master/numba/caching.py#L193) (within caching.py) mentions `numba.config.CACHE_DIR` that is [defined through the `NUMBA_CACHE_DIR` environment variable](https://github.com/numba/numba/blob/master/numba/config.py#L164) (and because the [StackOverflow entry](https://stackoverflow.com/questions/44183779/numba-caching-issue-cannot-cache-function-no-locator-available-for-file) also mentions it), I tried defining that environment variable as e.g. "/tmp". I also try defining [`NUMBA_DEBUG_CACHE`](http://numba.pydata.org/numba-doc/0.35.0/reference/envvars.html) environment variable to say `1`. But nope, it doesn't change things... 

Eventually I noticed that the culprit file mentioned on the last line of the RuntimeError (provided above by @fhoubie and similar in my case), and that is `venv/lib/python3.6/site-packages/py3dtiles-1.1.0-py3.6.egg/py3dtiles/points/distance.py`, gets displayed as regular file by the python machinery. But in fact `venv/lib/python3.6/site-packages/py3dtiles-1.1.0-py3.6.egg` is a ZIP data archive (binary file). I felt like this was a clue for making one the [`caching.py` available locators](https://github.com/numba/numba/blob/master/numba/caching.py#L328) (prior to [_IPythonCacheLocator](https://github.com/numba/numba/blob/master/numba/caching.py#L308)) fail but this didn't help much either...

**Comment by fhoubie** [comment] 2018-10-04 09:50
I have the same environment than @EricBoix .

**Comment by fhoubie** [comment] 2018-10-05 09:11
hi, I've done the installation on a completely clean/ new environment using vagrant ubuntu box and I have the same error

(venv) vagrant@postgresql:~/py3dtiles$ py3dtiles info tests/pointCloudRGB.pnts
Traceback (most recent call last):
  File "/home/vagrant/py3dtiles/venv/bin/py3dtiles", line 11, in <module>
    load_entry_point('py3dtiles==1.1.0', 'console_scripts', 'py3dtiles')()
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/command_line.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/convert.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/points/node.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/points/points_grid.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/points/distance.py", line 5, in <module>
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/numba/decorators.py", line 191, in wrapper
    disp.enable_caching()
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/numba/dispatcher.py", line 566, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/numba/caching.py", line 614, in __init__
    self._impl = self._impl_class(py_func)
  File "/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/numba/caching.py", line 349, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function 'is_point_far_enough': no locator available for file '/home/vagrant/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/points/distance.py'

**Comment by EricBoix** [comment] 2018-10-05 10:11
@fhoubie : what is the Ubuntu version that you used ? (I'm asking because I [failed to install on a Debian8](#28))

**Comment by fhoubie** [comment] 2018-10-05 10:27
@EricBoix I've installed a Ubuntu 16.04.5 LTS

**Comment by peppsac** [comment] 2018-10-05 13:56
> @fhoubie :
>> @EricBoix I've installed a Ubuntu 16.04.5 LTS

I just installed py3dtiles in a ubuntu 16.04 container, following the README instructions and it seems to work fine.

The `locator` used is `numba.caching._InTreeCacheLocator`, and it writes the cache in `/home/foo/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles/points/__pycache__` (for the `is_point_far_enough` function).

I realized that your path contains `.egg` elements (eg: py3dtiles-1.1.0-py3.5.egg). Did you install `py3dtiles` using `easy_install`?

It seems that `numba` caching strategies aren't compatible with `.egg` file, because they require file owning the cached function [to exist on the file system](https://github.com/numba/numba/blob/master/numba/caching.py#L178).

**Comment by EricBoix** [comment] 2018-10-05 14:58
@peppsac : 
I had the feeling (refer above) that the egg thingy had something to do with our trouble.

And to answer your question I did use `pip`(as documented in the Readme) and I did NOT use `easy_install`.

But the [best answer of this StackOverflow](https://stackoverflow.com/questions/27964960/pip-why-sometimes-installed-as-egg-sometimes-installed-as-files#29127158) mentions a way to inhibit the usage of  the `egg` mechanisms (that freezes numba cache).

So I just added the line
```
zip_safe = False
```
in the setup section of `Py3dTiles/setup.py` which seems to solve the numba cache problem.
Indeed the execution of `py3dtiles info tests/pointCloudRGB.pnts` now runs...a bit further...before hitting the next snag. :) 

I now get the following error
```
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(liblas_c.dylib, 6): image not found
``` 
which is a problem specific to my desktop's libblas install. After running (on OSX) `brew install liblas` (makes me wonder why this dependency is not pulled by the setup!?), the  **`py3dtiles info tests/pointCloudRGB.pnts` command runs smoothly**.

@peppsac: my humble recommendation would be to add the `zip_safe = False` line in Py3dTiles's setup.py file... Here goes the diff
```
iff --git a/setup.py b/setup.py
index 329b1ba..e2e806d 100644
--- a/setup.py
+++ b/setup.py
@@ -83,5 +83,6 @@ setup(
     },
     entry_points={
         'console_scripts': ['py3dtiles=py3dtiles.command_line:main'],
-    }
+    },
+    zip_safe = False
 )
```

**Comment by peppsac** [comment] 2018-10-05 15:27
> And to answer your question I did use pip(as documented in the Readme) and I did NOT use easy_install.

Ok (I asked because I had to use easy_install to reproduce the problem).

The `zip_safe` option seems like a good idea, I opened https://github.com/Oslandia/py3dtiles/pull/29 to merge this fix. Thanks!

**Closed as completed** 2018-10-08 07:32 UTC
